### ISSUE TITLE
wrong graphic on gl 2.1

### ISSUE THREAD

**Issue by tlosm** [xoreos/xoreos#122]
tested like some one ask on X5000 linux Ubuntu Mate 16.10
and because radeon hd 6xxx here on powerpc use only gl 2.1 (xorg  bug)
i have jade empire with wrong graphic 
atteched the console log.

in any way great job
[jade.txt](https://github.com/xoreos/xoreos/files/316897/jade.txt)

**Comment by DrMcCoy** [comment]
What exactly do you mean by "wrong graphics"? Could you fly around (using WASD to move and middle mouse button + mouse move to move the camera) and create some screenshots?

Currently, xoreos doesn't display the graphics correctly anyway, because shader support is missing. Compare to the screenshots on our website: https://xoreos.org/screenshots/index.html

I.e. the Two Rivers school in xoreos would look like this at the moment: https://xoreos.org/screenshots/jade/ingame01.png . If that is what you see, then this is "normal" at the moment. I don't see anything out of the ordinary in the log file either. (The "Unsupported TXB encoding 0x09" message is "normal" as well. We're still not sure how these textures are encoded; they're, presumably, lightmaps.)

**Comment by tlosm** [comment]
Hi DrMcCoy , do you see you asked i did :-)
yes i understand now  when i sow the screenshots in any way:
videos are working right.
gfx is glitched as you described 

let me know if you need more testing ;-)
ah... i can move the mouse and  the keyboard 
screen shoot attached is the main screen
![xor](https://cloud.githubusercontent.com/assets/18098090/16093347/d9225184-333b-11e6-9430-2413d8141210.png)

**Comment by DrMcCoy** [comment]
> Hi DrMcCoy , do you see you asked i did :-)

Yeah, thanks :)

Nice to see that xoreos works on Linux ppc. :)
Since it's all working as "normal", I'm closing this bug report.
