### ISSUE TITLE
BOOST: Compilation error using Visual Studio and Boost 1.69.0

### ISSUE THREAD

**Issue by seedhartha** [xoreos/xoreos#471]
I am unable to compile xoreos using Visual Studio and the latest version of Boost because of the following error:

[boost root]/boost/system/detail/system_category_win32.hpp(52): error C2039: 'c99_snprintf': is not a member of 'std'

The cause is this define in src/common/system.h:

#define snprintf c99_snprintf

Removing this line solves the issue. So does using an older version of Boost.

**Comment by DrMcCoy** [comment]
Ah, because MSVC prior to 2015 didn't implement snprintf (and _snprintf isn't 100% standards-compliant).

Beginning with Visual Studio 2015, they fixed that, it seems, and the `#if` in [system_category_win32.hpp:29](https://github.com/boostorg/system/blob/3a4fff686e81320d346304b978f866c4136bd863/include/boost/system/detail/system_category_win32.hpp#L29) reflects that.

I guess we should add an `#if _MSC_VER < 1900` block into the `#if defined(_MSC_VER)` in our system.h, and move the snprintf/vsnprintf compatibility code and defines there.

**Comment by DrMcCoy** [comment]
I.e. does this work for you? https://gist.github.com/DrMcCoy/c48da9ea93aa6a03451fc8bc3e7ee887

**Comment by seedhartha** [comment]
That does fix the issue. As a side note, I also tried compiling xoreos using MinGW, and CMake build fails with all sorts of undefined references at the linking stage (autotools works OK).

**Comment by seedhartha** [comment]
[Here](https://gist.github.com/seedhartha/968478ab690026cd9cc74cfa893be3ef) are the errors.

**Comment by DrMcCoy** [comment]
Hmm, I always cross-compile (using a cross-compiling MinGW on my Linux box) using autotools, never with CMake, yeah.

I'll investigate.

In the mean time, this original issue here is fixed then with f5ff1f167, I believe. :)

**Comment by DrMcCoy** [comment]
Hmmpf, I get can't really CMake to properly recognize my cross-compiler setup. I never really gelled with CMake :P

And I'm not sure the results would even be comparable to a MinGW on Windows. I guess I can't find a quick fix in 5 minutes. Please, open a new GitHub issue for this.
