### ISSUE TITLE
[macOS] Building on Arm / M1 / Apple Silicon requires extra cmake argument

### ISSUE THREAD

**Issue by shinra-electric** [xoreos/xoreos#580]
I was building xoreos on the M1, but cmake was failing.

I installed all required dependencies through homebrew, but it was not finding the SDL2 include directories. 

So I fixed it  by adding this extra argument: 

`-DSDL2_INCLUDE_DIR=/opt/homebrew/include/SDL2` 

I'm requesting either a modification to the cmake settings to search in this location, or else an update to the build instructions on the wiki.

**Comment by shinra-electric** [comment]
No, SDL2 is fine for anything else that is using it...

I did try using `brew doctor` and also reinstalled it as well, but it didn't work. 

If anyone else had an M1 (and uses homebrew), maybe they can test. 

If it's an issue with my install, that's fine. If not, well the fix is recorded here.

**Comment by DrMcCoy** [comment]
Yeah, it looks to me like homebrow changed something. The GitHub runners should be x86, yeah. As were the Travis CI macOS VMs, IRC, back when Travis CI was still alive.

I basically just moved over the information in the Travis CI config into GitHub Actions workflow. I don't really know a lot about the Apple ecosystem, so I'm mostly just guessing and messing with things until they work :). I personally don't have a Mac at the moment, even, unfortunately, nevermind an M1 one, so I can't really check.

Can you modify our `cmake/FindSDL2.cmake` file? In the `find_path` in the else-branch on line 32, can you add `/opt/homebrew/include/SDL2` to the HINTS paths?

I.e., replace that line with
```
find_path(SDL2_INCLUDE_DIR SDL.h HINTS /usr/include/SDL2 /usr/local/include/SDL2 /opt/local/include/SDL2 /opt/homebrew/include/SDL2 DOC "The directory where SDL.h resides")
```

Also, apart from this, can you also check using the autotools build system instead of cmake? Have a look at https://github.com/xoreos/xoreos/blob/master/.github/workflows/macos_autoconf_clang.yml#L24 to see how that is used. If that is broken on your system as well, this would also need to be fixed, I guess. We're using the sdl2-config script that SDL2 distributes there. If the configure script fails, please check where homebrew puts it

**Comment by shinra-electric** [comment]
Firstly, yes, replacing the line allows cmake to locate the includes correctly. 

Secondly, I haven't tried using the auto tools before so I'll just have a poke around and report back later.

**Comment by shinra-electric** [comment]
Yes, it looks like the configure script needs to be altered...

The autogen.sh ran fine. 
The configure script couldn't locate sdl2-config

`checking for sdl2-config... sdl2-config
configure: error: SDL2 (>= 2.0.0) is required and could not be found!`

running `which sdl2-config` in terminal gives me:   /opt/homebrew/bin/sdl2-config

**Comment by DrMcCoy** [comment]
Wait, if `which` can find it, it's in the PATH, so the configure script should also find it?

What does `sdl2-config --cflags --libs` output? And can you attach, upload or gist your config.log file?

**Comment by DrMcCoy** [comment]
Oh. That looks rather like a bug in our `ax_check_sdl2.m4` script.

Can you edit the file `m4/ax_check_sdl2.m4`, and change the line that says
```
#include <SDL2/SDL.h>
```
to
```
#include <SDL.h>
```
?

You need to rerun autogen.sh, and then the configure script. And then make, if configure runs through without error.

**Comment by shinra-electric** [comment]
We're getting close! 

No error from SDL2, but now I have one for Boost. 

`checking for Boost headers version >= 1.53.0... no`
`configure: error: cannot find Boost headers version >= 1.53.0`

**Comment by DrMcCoy** [comment]
Can you attach the config.log again? Thanks

And where does homebrew put the boost headers (and libraries)?

**Comment by shinra-electric** [comment]
[config.log](https://github.com/xoreos/xoreos/files/8063859/config.log)

Headers are in opt/homebrew/include/boost

Libraries are......I guess opt/homebrew/lib...? Check the screenshot here and see if these are the libraries you mean:

![Screenshot 2022-02-14 at 20 58 55](https://user-images.githubusercontent.com/50119606/153945625-9157926e-a983-48b9-87cf-b06ce2d35b85.png)

**Comment by DrMcCoy** [comment]
Yep, those are the libraries

Okay, so does homebrew not install anything into /usr/local/ anymore now?

**Comment by shinra-electric** [comment]
Don't quote me on this, but I think that's where homebrew puts x86 stuff. 

It's still a transition period, and it's common enough for people with M1s to still have to compile x86 versions of software and run through Rosetta.

**Comment by DrMcCoy** [comment]
Ah, okay, that makes sense. It's a bit annoying, though :P

Can you apply this patch and retry (starting with autogen.sh)? [homebrew_boost_m4.patch.txt](https://github.com/xoreos/xoreos/files/8064033/homebrew_boost_m4.patch.txt)

You'll apply those with `patch -p1 < homebrew_boost_m4.patch.txt`, in case you're not familiar with them.

**Comment by shinra-electric** [comment]
The scripts ran fine, and I was able to compile successfully. 

![Screenshot 2022-02-14 at 21 26 32](https://user-images.githubusercontent.com/50119606/153949149-9e0b7c25-34a1-4b3f-92a5-42165b7ee7e6.png)

Thanks :)

**Comment by DrMcCoy** [comment]
Nice :)

So in summary, what's needed is the following:
- Add /opt/homebrew to cmake/FindSDL2.cmake
- Add /opt/homebrew to m4/boost.m4
- Remove the extra SDL2 directory in the include directory in m4/ax_check_sdl2.m4

DId I miss anything?

The first two points are due to changes in homebrew for M1 Macs. While the latter one is actually a bug in our configure script that only didn't show any consequences before now.

(Or technically, it might a fault of SDL2, that their sdl2-config script shouldn't add the SDL2 directory to their include directive, but that's something they do on all platforms.)

And the first one makes our CMake build system work on M1 Macs, while the latter two make our autotools build systems works on M1 Macs.

I'll need to check that none of the changes break anything on my local cross-compilers, so a public fix in the repo might take a while. Just as a heads up. But in either case, thanks for finding those issues :)

**Comment by shinra-electric** [comment]
Yes, I think that’s it. 

👍🏼

**Comment by DrMcCoy** [comment]
Okay, fixed in https://github.com/xoreos/xoreos/compare/fa430d385103...87d09c68619e
