### ISSUE TITLE
Request: List of required files for each supported game

### ISSUE THREAD

**Issue by shinra-electric** [xoreos/xoreos#581]
I'm a bit OCD, so I generally don't like dumping the whole game install into the xoreos data folders. 
I would prefer if there was a list of exactly which files xoreos uses (for each game), so I can safely delete the irrelevant files. 

Related is that I have the Mac App Store versions of Kotor and Kotor2 that was released by Aspyr, as well as the official [restored content mod](https://www.aspyr.com/games/star-wars-knights-of-the-old-republic-ii-restored-content-mod), but xoreos doesn't seem to recognise these data folders. Are these data folders different enough that xoreos can't use them? Or is it just organised differently? (If there was a list of required files, I could sort through...)

**Comment by DrMcCoy** [comment]
Listing all necessary data files is on our agenda... once the games are supported far enough that we can definitely say which are necessary and which aren't. This is something for the future. Until then, it's best to have all of them present. And yes, that includes the original binaries for some games; the .exe files of the Windows versions of several games contain cursors, for example.

I'm not sure about the App Store versions of KotOR and KotOR2. However, the macOS Steam release of KotOR2 done by Aspyr should start: you need to point it at the directory that contains the GameData directory. If the App Store version is any similar, this should work.

Otherwise, this is something that needs to be implemented. Feel free to compare your directory tree with the Steam directory tree and/or match what you see in your version with `KotOR2Engine::initResources()` in src/engines/kotor2/kotor2.cpp:185 (and `KotOR2Engine::detectLanguages()` on lines 64ff). If you get it to work, we'd appreciate a pull request :)

Likewise, depending on the directory structure, something similar needs to be done for `KotOREngine`.

I do expect the directory structure to be similar in all these cases. The only exception might be KotOR2 for Android, with its new resource archive format (see #69). At least from how I understand the format at the moment, I can extract the files, but there's no directory structure at all.

**Comment by shinra-electric** [comment]
Fair enough, I'll hang on to all the files for now. (I'm pretty sure the gog related files are all unnecessary, as well as uninstallers and .ico files, so I'll satiate my ocd with getting rid of those).

Regarding the Mac app store versions of kotor and kotor2 I'll re-download them and compare the file structure with src/engines/kotor2/kotor2.cpp and src/engines/kotor/kotor.cpp. 

I'll close this issue until xoreos is further along. 

Thanks.
