### ISSUE TITLE
Main website

### ISSUE THREAD

**Issue by mischievous** [xoreos/xoreos#76]
Chrome and Safari keep blocking me from going to the main website.  Something about the security certificate responding with garbage.  Is there a mirror of the site I can download?

**Comment by DrMcCoy** [comment]
Yes, that's actually an issue with Mac OS X:
http://forums.macrumors.com/showthread.php?t=1387863
https://discussions.apple.com/thread/2668985?start=0&tstart=0

In short, Mac OS X doesn't like [certificates](https://en.wikipedia.org/wiki/Public_key_certificate) that are "too secure", meaning ones with an [RSA](https://en.wikipedia.org/wiki/RSA_%28cryptosystem%29) key >= 8192 bits. For reasons I frankly can't grasp, Mac OS X claims such a certficate, which is entirely valid, is broken.

The workaround found on those pages I linked above makes Mac OS X properly work with longer certificates. One thing though: xoreos.org doesn't use an RSA key with 8192 bits, but with 15424 bits. Alternatively, you can use Firefox, because Firefox doesn't use the Mac OS X SSL/TLS infrastructure.

For my reasons for using such a certificate: when I generated the key with [certtool](http://www.manpagez.com/man/1/certtool/), I used the option "--sec-param=ultra", because I though "Why not? More bits = more secure, right?". Well, I guess I now know the answer to that "Why not?".

Unfortunately, I'm stuck with that certificate for now. I used the [StartSSL](https://www.startssl.com/) service to sign the certificate for me, currently the only [CA](https://en.wikipedia.org/wiki/Certificate_authority) (that's accepted by all browsers) that doesn't take money to sign. They do, however, take money to revoke the certificate, $25 per. Since I use 2 certificates (one for [www.xoreos.org](https://www.xoreos.org/) that's also used for [xoreos.org](https://xoreos.org/), and one for [wiki.xoreos.org](https://wiki.xoreos.org/)), I would have to pay them $50 to revoke the certificates and create new ones. And I really don't feel like I should validate that business model by throwing money at them.

When the certificates expire (which is at the end of March), I will get ones with a weaker key, so that I won't run into this again. Additionally, I for one really hope [Let's Encrypt](https://letsencrypt.org/) takes off soon, because the current CA situation is pretty messed up. Let's Encrypt can hopefully fix this.

**Comment by petteyg** [comment]
Because >= 8192 bits means it takes more CPU time to decrypt and NSA decided the cost-effectiveness barrier for power:info ratio is below 8192 bits? :p

**Comment by DrMcCoy** [comment]
Well, it's the end of May (2 weeks before the certificates expire), and StartSSL let me renew them. I created ones with a 4096bit RSA key now, and so this issue should be fixed. I hope.

Please let me know if this works for you with Chrome and Safari now. Thanks. :)

**Comment by JanSimek** [comment]
Yes, it does work with Safari.

**Comment by DrMcCoy** [comment]
Neat :)
