### ISSUE TITLE
ENGINES: design decisions

### ISSUE THREAD

**Issue by cc9cii** [xoreos/xoreos#88]
Apologies in advance if these have been discussed already - if so kindly refer me to the relevant place - and we don't seem to have a forum area, so let me ask here please:

Do we have an agreed design in terms of how the engine will work, e.g. the kind of loop (single threaded, at least to start with?), whether third party physics engine will be used (bullet?), third party rendering engine (or are we rolling out our own in OpenGL, excluding those still on Windows with very poor OpenGL support), etc, etc

Related: is there a roadmap of which features should be tackled first?

**Comment by jbowtie** [comment]
There is a mailing list for general discussion. Many of the design decisions were made early on by  @DrMcCoy and haven't been revisited or discussed in depth.

It seems clear at this point that we are rolling our own engine. At the moment we're adding a more modern OpenGL rendering path but I haven't seen any deprecation of the existing old-school path.

As far as features go it's still pretty much 'whatever interests you'. Some not-too-difficult things that would probably make a big visible difference would be parsing (and then animating) model effects or loading/visualizing the walkmesh attached to tiles.

**Comment by DrMcCoy** [comment]
Yes, please don't open an issue for these kinds of discussion. The [mailing list](https://wiki.xoreos.org/index.php?title=Mailing_lists) exists exactly for this reason. :)

> the kind of loop (single threaded, at least to start with?)

Not really. Right now, the game logic does all run in a single loop for each engine. But the engine runs in its own game logic thread. If it proves useful, an engine is free to spawn its own threads.

> whether third party physics engine will be used

As long as the libraries are FLOSS and portable, they're fair game. No need to duplicate work, if not strictly necessary.

I'm not sure we're going to need an elaborate physics engine though; the BioWare games we target don't really use one themselves, unless I'm mistaken.

> third party rendering engine

We are very much rolling our own (or rather, @mirv-sillyfish is the person bringing the renderer up to speed, rewriting my naive OpenGL code). And yes, I do think OpenGL is the way to go; I don't really want to focus too much on the proprietary Microsoft-only Direct3D.

As for a third-party rendering engine...well, I tried that for the better part of a year, looking at Irrlicht and OpenSceneGraph, finding them lacking in features we need, then trying to hammer xoreos into Ogre3D, with middling success. The now abandoned feature-branch ogrewip speaks of that experiment. It was not happy-happy fun time for me.

> is there a roadmap of which features should be tackled first

As @bjowtie said, it's a free-for-all at the moment. Although I would like if you could annoucement what you want to work on early, either on the mailing list or on IRC. I want to keep track of that, so that we don't end up with several people working on the same thing. :)

In general, yes, walkmeshes for NWN would be one thing. Someone also previously suggested a FLOSS pathing library that could help doing the pathing ones the walkmeshes are there; need to look through my logs to see which one it was.

Another easy-ish entry could be a broken-XML parser needed to NWN2. We'll also need a real XML parser for Dragon Age, and I've been thinking about probably linking to libxml2, but I doubt you can bring it to not throw errors left and right on the broken NWN2 XML files, unfortunately.

As for anything related to scripts, I would like to ask you to wait on @ImperatorPrime there, who's currently rewriting the script system. The current script system is a bit awkward, because I lost track of what i actually wanted to accomplish with it, and left it with a basically unnessary boost::bind() usage.
