### ISSUE TITLE
WIN32: Fix CMake definitions for iconv

### ISSUE THREAD

**Issue by darkstar** [xoreos/xoreos#92]
Here's a small patch which fixes compilation on Windows with MSVC:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 31bc1b3..8d1d8ea 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -30,7 +30,7 @@ elseif(CMAKE_HOST_UNIX)
   string(REPLACE "<LINK_LIBRARIES>" "-Wl,--start-group <LINK_LIBRARIES> -Wl,--end-group" CMAKE_C_CREATE_SHARED_MODULE "${CMAKE_C_CREATE_SHARED_MODULE}")
   string(REPLACE "<LINK_LIBRARIES>" "-Wl,--start-group <LINK_LIBRARIES> -Wl,--end-group" CMAKE_CXX_CREATE_SHARED_MODULE "${CMAKE_CXX_CREATE_SHARED_MODULE}")
 elseif(CMAKE_HOST_WIN32)
-
+  add_definitions(-DICONV_CONST=)
 else()
   message(STATUS "Unknown platform, maybe not supported")
 endif() 
```
Problem is that in ```common/encoding.cpp```, the symbol (macro) ```ICONV_CONST``` is used. However, on Win32 with MSVC, that symbol is not defined, leading to a compilation error. It should be defined to the empty string (just like for UNIX a few lines above in CMakeLists.txt) so that the preprocessor accepts it.

Another solution would be to drop the ICONST_CONV macro from ```common/encoding.cpp```

**Comment by DrMcCoy** [comment]
Well, the ICONST_CONV macro is important, unfortunately, so dropping it is really not an options. The issue is that the iconv() signature can differ slightly for different implementations.

GNU libiconv generally uses
```size_t iconv(iconv_t cd, char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);```
while other implementations might use
```size_t iconv(iconv_t cd, const char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);```
Note the const at the second parameter inbuf. I'm not quite sure which implementation to that, though. The BSDs?

A different option might be to define ICONV_CONST to empty (or const?) when undefined, in system.h or something. Depending on how prevelant each option is, that'll at least give us some fallback? But maybe that's not as great as manually making sure it's defined to the *correct* value for each platform... Dunno.

In either case, I commited your fix. Thanks! :)

**Comment by darkstar** [comment]
I haven't tried it but shouldn't ```const char**``` and ```char **``` be compatible? As in "if the library requires const char ** and the program gives a char ** it will work"? Because, the argument being const just means that the library doesn't change it, if the program provides a pointer that *could* be changed, that shouldn't cause and problems, right?

**Comment by DrMcCoy** [comment]
Nope, C++ does not allow the automatic conversion from char ** to const char **. See also [this entry in the C++ FAQ](https://isocpp.org/wiki/faq/const-correctness#constptrptr-conversion), and the other entries in this part of the FAQ for more details on const correctness.

Try it yourself:
```
#include <cstring>

int bar1(char **x) {
	return 1;
}

int bar2(const char **x) {
	return 2;
}

int main(void) {
	char *foo = new char[5];
	memset(foo, 0, 5);

	bar1(&foo);
	bar2(&foo);

	return 0;
}
```

That will give this error on compilation:

```
foo.cpp: In function ‘int main()’:
foo.cpp:16:11: error: invalid conversion from ‘char**’ to ‘const char**’ [-fpermissive]
  bar2(&foo);
           ^
foo.cpp:7:5: note:   initializing argument 1 of ‘int bar2(const char**)’
 int bar2(const char **x) {
     ^
```

That's why the explicit cast to ```const char **``` is necessary for iconv() taking a ```const char **```. And because the other way round, ```const char **``` to ```char **```, isn't allowed either, the cast is to ```ICONV_CONST char **``` with ```ICONV_CONST``` evaluting to either ```const``` or empty. Granted, that's not really a beautiful solution, but it works.
