### ISSUE TITLE
[Suggestion] Opensuse build service

### ISSUE THREAD

**Issue by malkavi** [xoreos/xoreos#93]
For test builds for different distros you can use build service. (ubuntu, opensuse. centos...)
I have been playing with the service and xoreos :P
But I haven't had time to test the binary... sorry.
My repo for opensuse 13.2:
https://build.opensuse.org/package/show/home:malkavi/xoreos

**Comment by DrMcCoy** [comment]
Oh, that *is* pretty neat, thanks. :)

If I understand it correctly, apart from test builds, I could use their reference server to build xoreos release packages for different distributions, right?

I see that the openSUSE_13.1 build fails because boost.m4 fails to find boost.atomic. Is there a way to get the config.log created by the configure script somehow? I suspect it's related to the broken intptr_t/uintptr_t situation in some versions of Boost (which has been fixed in later versions). I thought I was successfully working around that (by #include'ing unistd.h and stdint.h before the boost atomic headers, and moving the CXX-PROLOGUE to the top in boost.m4), but I guess I broke it again.

**Comment by DrMcCoy** [comment]
Ugh, just downloaded the VMWare image of OBS, to see if I can run it locally (in VirtualBox), to privately play around with it a bit.

Yeah, no chance in hell I can do that on my system with 4GB of RAM. I can't really give the VM more than 2GB, and even with that, it constantly swaps and kills random stuff through the OOM killer, already while doing the initial setup phase. Nevermind running a gcc ontop of this.

The VMWare config it comes with says 1GB of RAM, but I can't even log into the web interface then. 2GB works for a while, but one web interface log out / log in cycle later, it's dead again.

As long as I can use their public reference installation, okay, but I don't have the hardware to run it locally. :P

**Comment by malkavi** [comment]
I can't find a way to download the config.log file after the error. But I will try to find a way.

I haven't tried the image, my system is not powerful enough. :P

**Comment by DrMcCoy** [comment]
IIRC, while debugging Travis CI, we added a "cat config.log" to the build instructions. Not the cleanest way to get the file, but worked. Maybe you can do something similar.

**Comment by malkavi** [comment]
I have a VM with openSUSE 13.1 at work.... it's a secret XD
There is the config.log
http://pastebin.com/f2Q1mBbF

**Comment by DrMcCoy** [comment]
Huh, it just straight-up can't find boost_atomic. It finds Boost.Filesystem as boost_filesystem-mt, but checking for boost_atomic-mt fails.

Can you check that there *is* a libboost_atomic-mt.so in the same place where there is a libboost_filesystem-mt.so? Maybe it's not installed by default on OpenSuSE 13.1 for some reason, and you need to install the package (and/or the -devel package).

**Comment by malkavi** [comment]
Done. I have added the library only for 13.1 and now It's compiled without problems.

**Comment by DrMcCoy** [comment]
Oh, okay. :)

**Comment by DrMcCoy** [comment]
Okay, I played around with it myself for the last two days.

xoreos and xoreos-tools seem to build now for different distributions:
https://build.opensuse.org/package/show/home:DrMcCoy:xoreos/xoreos
https://build.opensuse.org/package/show/home:DrMcCoy:xoreos/xoreos-tools

A few issues, though: OBS is missing all of universe for Ubuntu. Which means sdl2, xvidcore, mad and faad were missing. No problem; I just added them. But also missing are, for some infuriating reason, libboost-atomic-dev and libboost-locale-dev. And boost doesn't build within OBS, because they don't have enough memory (gcc abort with "Cannot allocate memory" in the middle of the build).

libboost-atomic1.54-dev / libboost-atomic1.55-dev is main, so I added an empty package fake package emulating the libboost-atomic-dev dependency forward. libboost-locale is completely missing from main, so I added fake packages containing the precompiled library binaries. This all works. But: the Ubuntu packages of xoreos is then missing the dependencies on boost-atomic and boost-locale. I can't think of a way to add them manually without then also adding them to Debian (also, how to handle the 1.54/1.55 difference in the different Ubuntu versions), because it seems debian.control can't be distribution-versioned like the .dsc file.

**Comment by DrMcCoy** [comment]
Hmm, just saw a boost package in OBS with a "_constraints" file, that says it should only run on workers with a least 2GB of RAM. Maybe that'll work...

**Comment by DrMcCoy** [comment]
Yeah, when a worker with more memory (the next step up seem to be 7GB for the public OBS installation) grab up the package, it builds

**Comment by malkavi** [comment]
Then the packages for Ubuntu, openSuse, Fedora, Debian and Arch, are ready?
I didn't know about the "_constraints" trick, very useful. Now you need a (better) description for the package in the repo. ;)

**Comment by DrMcCoy** [comment]
rpmlint also complains about missing manpages (for xoreos, and for the 15 binaries in xoreos-tools). Maybe I should write those.

And lintian is also complaining. Not sure how many of those I can fix (since they seem to be in stuff OBS generates?). Of course, I *could* remove the debian.* files and instead provide a complete packed debian directory...

If I do the later, writing a complete debian directory, I could even drop that into the xoreos repo and treat it like the official debian build source. Similarily, I could also do that with a proper PKGBUILD.

**Comment by DrMcCoy** [comment]
Okay, as a status update for anybody who hasn't noticed:

- I did write manpages for all programs in xoreos-tools and for xoreos itself
- I added a Debian build directory and a PKGBUILD to both xoreos and xoreos-tools
- Providing a real debian directory does not work with OBS (unless you also drop in a static orig tar.gz, instead of having it automatically check out the git repository)
- Right now, lintian has been completely removed from the OBS build scripts, so that point is kinda moot as well
- OBS builds xoreos and xoreos-tools 0.0.2 fine now, for various distributions
- I submitted the PKGBUILDs to Arch's AUR

Thanks again for pointing me at OBS, @malkavi. :)
