### ISSUE TITLE
cmake: liblzma was not found

### ISSUE THREAD

**Issue by wahrhaft** [xoreos/xoreos#97]
When running cmake, I get the following error:

`liblzma was not found. Make sure LIBLZMA_LIBRARY and LIBLZMA_INCLUDE_DIR are set.`

I had liblzma installed, so I checked cmake/FindLibLZMA.cmake and found this line:

`find_library(LIBLZMA_LIBRARY NAMES liblzma DOC "The liblzma library")`

Replacing it with this line fixed the problem:

`find_library(LIBLZMA_LIBRARY NAMES lzma DOC "The liblzma library")`

I'm using cmake version 3.2.3 on Arch Linux.
The cmake files in phaethon also have the same issue.

**Comment by DrMcCoy** [comment]
Ah, I had the same issue, but assumed it had to do with my Debian unstable system. xoreos still links without (because the BZFFile class that uses lzma isn't hooked up anywhere), only Phaethon fails to link.

Googling a bit, it seems like the usually way to search for lzma in CMake is to specify both names, lzma and liblzma, and CMake will check for the one first, and if it's not found, try the other name. I'll fix it with that, then. Unless there's a good reason to not do that (ping @berenm)?

Thanks for reporting! :)

**Comment by berenm** [comment]
Looks good to me.
